telegram:
  api-url: "https://api.telegram.org/"
  bot-name: "NASAPic_bot"
  bot-token: "${BOT_TOKEN}"
  webhook-path: "https://5d67-178-134-101-193.ngrok-free.app"
  bot-path: ""
server:
  port: "80"
message:
  errorText:
    text: "Почему-то не сработало."
translate: false
yandex-api:
  api-url: "https://translate.api.cloud.yandex.net/translate/v2/translate"
  folder-id: "b1gh84dl01a0jkghcf9b"
  api-token: "${YA_API_TOKEN}"
apod:
  api-url: "https://apod.ellanan.com/api"

logging:
  level:
    root: INFO
    org.springframework: ERROR
    space.maxkonkin.nasapicbot: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"