telegram:
  api-url: "https://api.telegram.org/"
  bot-name: "NASAPic_bot"
  webhook-path: "https://601f-178-134-101-193.ngrok-free.app"
  bot-path: ""
server:
  port: "80"
message:
  errorText:
    text: "Почему-то не сработало"

logging:
  level:
    root: INFO
    org.springframework: ERROR
    ru.konkin.telegram.NASAPicOnSpringBot: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"